--EDA USING SQL

ROLLBACK;

SELECT * FROM customer;
--Total revenue generated by male and female
SELECT "Gender", SUM("Purchase Amount (USD)") AS revenue
FROM customer
GROUP BY "Gender";

--Customers that used a discount but spent more than average
SELECT cid, amount
FROM (
    SELECT 
        "Customer ID" AS cid,
        "Purchase Amount (USD)" AS amount,
        "Discount Applied" AS discount
    FROM customer
) c
WHERE c.discount = 'Yes'
  AND c.amount >= (SELECT AVG("Purchase Amount (USD)") FROM customer);

--Top 5 products with highest avg review rating
WITH c AS (
    SELECT  
        "Item Purchased" AS item,
        "Review Rating"::numeric AS rating
    FROM customer
)
SELECT item, 
       ROUND(AVG(rating), 2) AS avg_rating
FROM c
GROUP BY item
ORDER BY avg_rating DESC
LIMIT 5;

--Average Purchase Amounts between Standard and Express Shipping. 
WITH c AS (
    SELECT 
        "Shipping Type" AS shipping,
        "Purchase Amount (USD)" AS amount
    FROM customer
)
SELECT shipping,
       ROUND(AVG(amount), 2) AS avg_amount
FROM c
WHERE shipping IN ('Standard','Express')
GROUP BY shipping;

--Do subscribed customers spend more?
WITH c AS (
    SELECT 
        "Subscription Status" AS subscription,
        "Customer ID" AS cid,
        "Purchase Amount (USD)" AS amount
    FROM customer
)
SELECT subscription,
       COUNT(cid) AS total_customers,
       ROUND(AVG(amount),2) AS avg_spend,
       ROUND(SUM(amount),2) AS total_revenue
FROM c
GROUP BY subscription
ORDER BY total_revenue DESC, avg_spend DESC;

--Top 5 products with highest discount rate
WITH c AS (
    SELECT 
        "Item Purchased" AS item,
        "Discount Applied" AS discount
    FROM customer
)
SELECT item,
       ROUND(100.0 * SUM(CASE WHEN discount = 'Yes' THEN 1 ELSE 0 END)/COUNT(*), 2)
       AS discount_rate
FROM c
GROUP BY item
ORDER BY discount_rate DESC
LIMIT 5;

--Customer Segments: New / Returning / Loyal
WITH c AS (
    SELECT  
        "Customer ID" AS cid,
        "Previous Purchases" AS prev_purchases
    FROM customer
),
segments AS (
    SELECT cid,
           prev_purchases,
           CASE 
               WHEN prev_purchases = 1 THEN 'New'
               WHEN prev_purchases BETWEEN 2 AND 10 THEN 'Returning'
               ELSE 'Loyal'
           END AS segment
    FROM c
)
SELECT segment,
       COUNT(*) AS num_customers
FROM segments
GROUP BY segment;

--Top 3 most purchased products per category
WITH c AS (
    SELECT 
        "Category" AS category,
        "Item Purchased" AS item,
        "Customer ID" AS cid
    FROM customer
),
counts AS (
    SELECT category,
           item,
           COUNT(cid) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(cid) DESC) AS rn
    FROM c
    GROUP BY category, item
)
SELECT category, item, total_orders
FROM counts
WHERE rn <= 3;

--Are repeat buyers (> 5) more likely to subscribe?
WITH c AS (
    SELECT
        "Subscription Status" AS subscription,
        "Previous Purchases" AS prev_purchases,
        "Customer ID" AS cid
    FROM customer
)
SELECT subscription,
       COUNT(cid) AS repeat_buyers
FROM c
WHERE prev_purchases > 5
GROUP BY subscription;

--Revenue contribution by age group
WITH c AS (
    SELECT 
        "Age" AS age_group,
        "Purchase Amount (USD)" AS amount
    FROM customer
)
SELECT age_group,
       SUM(amount) AS total_revenue
FROM c
GROUP BY age_group
ORDER BY total_revenue DESC;

